project_id = "fpbvnrxrmesxgnaxkiua"

[functions.extract-invoice]
verify_jwt = false

[functions.extract-bank-pdf]
verify_jwt = false

[functions.send-proforma-email]
verify_jwt = false

[functions.accountant-portal-access]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.ai-match]
verify_jwt = false

[functions.notify-admin]
verify_jwt = false

[functions.verify-afm]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-monthly-reminder]
verify_jwt = false

[functions.notify-team-invoice]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.ai-advisor]
verify_jwt = false

[functions.ai-insights]
verify_jwt = false
